# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flach to Reality
email: ryanflach@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A written record of the thoughts I choose to make public and easily accesible
  via a blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryanflach.github.io" # the base hostname & protocol for your site
twitter_username: ryan_flach
github_username:  ryanflach

# Build settings
markdown: kramdown
